# Generated by Django 3.1.6 on 2021-02-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210206_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='post',
            name='reads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
