# Generated by Django 3.1.6 on 2021-02-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210207_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.AlterField(
            model_name='post',
            name='reads',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
